# To run: conda env create -f environment.yml
name: code_1
channels:
    - conda-forge
dependencies:
    - python=3.8
    - pytorch=1.5.1
    - pyyaml=5.3.1
    - numpy=1.18.5
    - tqdm=4.48.0
